apiVersion: v1
kind: ReplicationController
metadata:
  name: cidev-svc
spec:
  replicas: 1
  selector:
    name: cidev-svc
  template:
    metadata:
      labels:
        name: cidev-svc
    spec:
      containers:
        - name: cidev-svc
          image: registry.isspaas.com/cityinsight/cidev-svc:latest
          imagePullPolicy: Always
          env:
            - name: DUBBO_REGISTRY_ADDRESS
              value: "kube://zookeeper:22181"
            - name: DUBBO_REGISTRY_REGISTER
              value: "true"
          ports:
            - containerPort: 8888

