apiVersion: v1
kind: ReplicationController
metadata:
  name: cidev-svc
spec:
  replicas: 1
  selector:
    name: cidev-svc
  template:
    metadata:
      labels:
        name: cidev-svc
    spec:
      containers:
        - name: cidev-svc
          image: registry.isspaas.com/cityinsight/cidev-svc:latest
          imagePullPolicy: Always
          env:
            - name: DUBBO_REGISTRY_ADDRESS
              value: "kube://10.16.117.161:22181"
            - name: DUBBO_REGISTRY_REGISTER
              value: "true"
            - name: DUBBO_PROTOCOL_KUBE_HOST
              value: "10.16.117.161"
            - name: DUBBO_PROTOCOL_KUBE_PORT
              value: "31888"

          ports:
            - containerPort: 8888

